### PR TITLE
implementing file menu functionality

### PR DESCRIPTION
**Pull request by alex-mulkerrins**
Implementing file menu functionality:
- New Scene
- Open Scene
- Save scene
        - Will check if there is already a FilePath in memory, otherwise will call 'Save As'
- Save As Scene

-New / open project will be implemented when further UI is implemented.
-'Build settings' & 'Build and run' will be one of the last things as this will be how you build the executable, further features are needed before this can be done 
Screenshot 2022-11-08 131601

### CODE REVIEW

**Review by LiamANeeson — APPROVED** [review]
LGTM!

**Review by prajakta-kulkarni-git — APPROVED** [review]
Looks good.

**Comment by BozhidarVelikov** [comment]
When you create a new scene, also set the EditorLayer Scene variable, so that the new scene is opened automatically when you create it.

**Comment by alex-mulkerrins** [comment]
> When you create a new scene, also set the EditorLayer Scene variable, so that the new scene is opened automatically when you create it.

Are you refering to 'std::string SceneFilePath;' in HznApp.h?

**Comment by alex-mulkerrins** [comment]
Ok I think that should sort the issue
Line 431 -> 435 of HznApp.cpp

**Review by BozhidarVelikov — APPROVED** [review]
Yeah, that solves it. Great work!

**Pull request merged**
