### PR TITLE
Preliminary Render Abstraction Update + Separation of Entry point header from other public API headers.

### PR DESCRIPTION
**Pull request by TejasJD**
Firstly, the preliminary abstraction of Render API is done. So now, it completely abstracts the implementation from the user, and depending on the choice of your rendering backend, right implementations are bound to this Rendering interface.
Second, I've separated the entry point header, from rest of the public API header (previously resided in HorizonEngine.h). This has two benefits:
- It allows us to use public API header in multiple source files.
- The HznEntryPoint.h or the entry point header should only be included in one of the source files. It provided a readability benefit as well, in the sense that, it tells the Reader of client application, where the application's entry point is.

### CODE REVIEW

**Comment by BozhidarVelikov** [comment]
I like the abstraction layer on top of the OpenGL API.

Also, I had difficulties earlier in finding where the starting point of the application is, so this separation of the headers is a good idea.

**Review by BozhidarVelikov — APPROVED** [review]

**Comment by alex-mulkerrins** [comment]
I see the windows platform has been removed to provide the OpenGL structure, do we want to keep a general windows directory for all future windows dependent things in the platform directory or will we keep things organised by feature?

**Review by alex-mulkerrins — APPROVED** [review]

**Comment by TejasJD** [comment]
> I see the windows platform has been removed to provide the OpenGL structure, do we want to keep a general windows directory for all future windows dependent things in the platform directory or will we keep things organised by feature?

I think we can keep that, in the future. Like, you can add the Windows Directory in the platform, and organize the concrete implementations, which use windows only components (like implementations that use the Win32 api), in that. For now, I've just kept the OpenGL folder, since there was nothing to be kept in the Windows directory yet. But once you have the concrete implementations ready, we can add those along with the Windows directory.

**Comment by alex-mulkerrins** [comment]
Ok I see what you mean, I think I was on the right track for this anyway in terms of the win32 API file dialogs being implemented.

**Comment by Minghui-Gao** [comment]
Very good work！

**Review by Minghui-Gao — APPROVED** [review]
I think you can merge now

**Pull request merged**
